eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
spring:
  application:
    name: user-server2
server:
  port: 8767

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillseconds: 2000