eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: user-eureka

