spring:
  application:
    name: user-server1
server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
feign:
  hystrix:
    enabled: true   #启动feign-hystrix
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000

