eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
spring:
  application:
    name: sso
  datasource:
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sso
         #格式为：lb://应用注册服务名
          uri: lb://USER-SERVER2/hello
          predicates:
            - Path=/hello
          filters:
            - StripPrefix= 1


#  redis:
#    cluster:
#      nodes: 127.0.0.1:6379,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
server:
  port: 8877
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.springframework.cloud.gateway: debug

#zuul:
#  prefix: /api/**
#  routes:
#    sso-server:
#        path: /user/**
#        serviceId: sso-server
